### ISSUE TITLE
Negated query support. 

### ISSUE THREAD

**Issue by pryorda** [jessfraz/gmailfilters#3]
It noticed that we are missing Negated Query support. I added the negated support in my PR #2. Do you feel I should cherry pick the commit or is there a better way to handle this?

https://github.com/pryorda/gmailfilters/commit/843dbffdafb1314fbafd9be949049ef31557a85f

**Comment by jessfraz** [comment]
oh sure thing please open a PR with that, sorry for missing that! Thanks!

**Comment by pryorda** [comment]
Np. will do so shortly!

**Comment by pryorda** [comment]
@jessfraz Looks like #6 will capture the negated query for me and all other fields. Thanks @seankhliao
